name: Build Check on Pull Request

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CURRENT_VERSION: 1.1.2
  PREVIOUS_VERSION: 1.1.1
  SERVICE_NAME: nestjs-backend-project

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vdr-services:${{ env.SERVICE_NAME }}-${{ env.CURRENT_VERSION }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/vdr-services:${{ env.SERVICE_NAME }}-${{ env.CURRENT_VERSION }} ${{ secrets.DOCKER_USERNAME }}/vdr-services:latest

      - name: Push Docker images
        run: |
          docker push jyotipm17/vdr-services:${{ env.SERVICE_NAME }}-${{ env.CURRENT_VERSION }}
          docker push jyotipm17/vdr-services:latest

      - name: Save version info
        run: |
          echo "CURRENT_VERSION=${{ env.CURRENT_VERSION }}" >> $GITHUB_ENV
          echo "PREVIOUS_VERSION=${{ env.PREVIOUS_VERSION }}" >> $GITHUB_ENV