name: Docker Deployment Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to rollback to (e.g. 1.1.0)'
        required: true
      service:
        description: 'Service name to rollback'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy rollback on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Login to Docker Hub
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            # Pull the previous version
            sudo docker pull jyotipm17/vdr-services:${{ github.event.inputs.service }}-${{ github.event.inputs.version }}
            
            # Stop current container
            sudo docker stop ${{ github.event.inputs.service }}-${{ github.event.inputs.version }} || true
            sudo docker rm ${{ github.event.inputs.service }}-${{ github.event.inputs.version }} || true
            
            # Start container with previous version
            sudo docker run -d --name ${{ github.event.inputs.service }}-${{ github.event.inputs.version }} \
              -p ${{ secrets.APP_PORT }}:3000 \
              jyotipm17/vdr-services:${{ github.event.inputs.service }}-${{ github.event.inputs.version }}
            
            # Verify rollback
            sudo docker ps | grep ${{ github.event.inputs.service }}-${{ github.event.inputs.version }}