name: Docker Deployment Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to rollback to (e.g. 1.1.2)'
        required: true
        default: '1.1.2'
      service:
        description: 'Service name to rollback'
        required: true
        default: 'nestjs-backend-project'

jobs:
  rollback:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy rollback on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Verify Docker is running
            sudo systemctl status docker || sudo systemctl start docker
            
            # Login to Docker Hub
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            # Pull previous version
            echo "Rolling back to version ${{ github.event.inputs.version }}"
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/vdr-services:${{ github.event.inputs.service }}-${{ github.event.inputs.version }}
            
            # Stop current container (1.1.3)
            sudo docker stop ${{ github.event.inputs.service }}-1.1.3 || true
            sudo docker rm ${{ github.event.inputs.service }}-1.1.3 || true
            
            # Start previous version (1.1.2)
            sudo docker run -d \
              --name ${{ github.event.inputs.service }}-${{ github.event.inputs.version }} \
              -p ${{ secrets.APP_PORT }}:3000 \
              ${{ secrets.DOCKER_USERNAME }}/vdr-services:${{ github.event.inputs.service }}-${{ github.event.inputs.version }}
            
            # Verify rollback
            sudo docker ps | grep ${{ github.event.inputs.service }}